language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '14'

git:
  depth: 3


deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 07cf3d97-53ad-43c6-8d12-2b35bc8676f0 
  app: typebot-api-gateway
  on:
    repo: michaeladrianhernandezrala/typebot-api-gateway
    branches:   
      only:      
        - main 